eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.11:28761/eureka/
    healthcheck:
      enable: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 10
    # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 30
    hostname: 192.168.0.11
logging:
  config: classpath:log4j-pro.xml
spring:
  jedis:
    host: 192.168.0.11
    port: 26379
    maxIdle: 10
    maxWaitMillis: 100000