eureka:
  client:
    service-url:
      defaultZone: http://localhost:28761/eureka/
    healthcheck:
      enable: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 10
    # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 30
    hostname: localhost
# 公钥
public:
  key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKi3CAdSvKZs6IaqfseFh8V4CDD1GZFlKejhRPGNf1YWLK/K8aArMEWSfZLnnsGY7eqz88btsXcFMpG8vhbxOXECAwEAAQ==
spring:
  datasource:
    username: tland
    password: Ap38J6n2hnlbyGnAGnc95zh9c70SoNJZlYGLRThyficOK/4s3UYI0xijTlVQbG69zh13aW0FZ860YhaFVg5SRg==
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.0.11:21000/tland?autoReconnect=true&useSSL=false
    initial-size: 1
    min-idle: 1
    max-active: 50
    test-on-borrow: true
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-While-Idle: true
    test-on-return: false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,config
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=${public.key}
    monitor:
      enabled: false
      druid-stat-view: /druid/*
      druid-web-stat-filter: /*
      allow: 127.0.0.1
      deny: 192.168.0.174
      login-username: user
      login-password: 123456
      exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      reset-enable: false
logging:
  config: classpath:log4j-dev.xml
