eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.11:28761/eureka/
    healthcheck:
      enable: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 10
    # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 30
    hostname: 192.168.0.11
logging:
  config: classpath:log4j-pro.xml
security:
  token:
    expirationTime: 7200
    issuer: QUANTENG@TLAND
    signingKey: quanteng@tland@2018
    refreshExpTime: 120000
  keys:
    secretId: RCIDc5756c536a394dd18e459dc0a17b3b78
    secretKey: c9b98cf884d641beaa03756beb067ce0